
import React from 'react';
import { 
  Search, 
  Home, 
  ArrowLeft, 
  ArrowRight, 
  RotateCw, 
  Star, 
  Menu, 
  CheckSquare, 
  FileText, 
  BrainCircuit, 
  StickyNote, 
  Layers, 
  Youtube, 
  Send, 
  BookOpen,
  GraduationCap,
  X,
  Plus,
  Minus,
  Download,
  Trash2,
  FolderOpen,
  Folder,
  Library,
  Clock,
  Bookmark,
  Puzzle,
  Play,
  Pause,
  Square,
  Calendar,
  Repeat,
  ArrowUpRight,
  Copy,
  Video,
  MapPin,
  Shield,
  Lock,
  Unlock,
  AlertTriangle,
  ChevronUp,
  ChevronDown,
  ChevronRight,
  Settings,
  Palette,
  Monitor,
  MoreVertical,
  Globe,
  Eye,
  EyeOff,
  Edit2,
  Image,
  Code,
  LayoutGrid,
  List,
  MoreHorizontal,
  Link,
  MousePointer2,
  CornerDownRight,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  Highlighter,
  Type,
  ListOrdered,
  Smile,
  Indent,
  Maximize,
  Minimize,
  Move,
  MousePointer,
  Quote,
  Hash,
  PenTool,
  Eraser,
  Hand,
  Save,
  FilePlus,
  Zap,
  Network,
  Lightbulb,
  CalendarDays,
  CalendarCheck,
  Notebook,
  Pilcrow,
  WalletCards,
  RefreshCcw,
  CopyPlus,
  MinusCircle,
  AppWindow,
  Telescope,
  SearchCode,
  Speech,
  MessageSquareQuote,
  BookmarkPlus,
  Scissors,
  Clipboard,
  Target,
  RotateCcw,
  Circle,
  Bell
} from 'lucide-react';

const icons = {
  // Navigation & General
  search: Search,
  searchCode: SearchCode,
  telescope: Telescope,
  home: Home,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  externalLink: ArrowUpRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  menu: Menu,
  moreVertical: MoreVertical,
  moreHorizontal: MoreHorizontal,
  x: X,
  plus: Plus,
  minus: Minus,
  minusCircle: MinusCircle,
  settings: Settings,
  checkSquare: CheckSquare,
  clock: Clock,
  calendar: Calendar,
  calendarDays: CalendarDays,
  calendarCheck: CalendarCheck,
  appWindow: AppWindow,
  bell: Bell,
  
  // Media & Content
  play: Play,
  pause: Pause,
  stop: Square,
  video: Video,
  image: Image,
  youtube: Youtube,
  speech: Speech,
  messageSquareQuote: MessageSquareQuote,
  
  // Documents & Notes
  fileText: FileText,
  note: StickyNote,
  notebook: Notebook,
  list: List,
  listOrdered: ListOrdered,
  brain: BrainCircuit,
  mindmap: Network,
  network: Network,
  book: BookOpen,
  library: Library,
  folder: Folder,
  folderOpen: FolderOpen,
  clipboard: Clipboard,
  
  // Cards Identity
  cards: WalletCards, 
  flashcards: WalletCards,
  deck: WalletCards,
  
  layout: LayoutGrid,
  layers: Layers,
  quote: Quote,
  hash: Hash,
  pilcrow: Pilcrow,
  
  // Tools
  pencil: PenTool,
  pen: Edit2,
  eraser: Eraser,
  hand: Hand,
  save: Save,
  filePlus: FilePlus,
  bookmarkPlus: BookmarkPlus,
  zap: Zap,
  lightbulb: Lightbulb,
  scissors: Scissors,
  target: Target,
  circle: Circle,
  
  // Actions
  edit: Edit2,
  edit2: Edit2,
  copy: Copy,
  copyPlus: CopyPlus,
  duplicate: CopyPlus,
  trash: Trash2,
  delete: Trash2,
  download: Download,
  refresh: RefreshCcw,
  rotateCw: RotateCw,
  rotateCcw: RotateCcw,
  refreshCcw: RefreshCcw,
  link: Link,
  connect: CornerDownRight,
  star: Star,
  favorite: Star,
  bookmark: Bookmark,
  cursor: MousePointer2,
  indent: Indent,
  maximize: Maximize,
  minimize: Minimize,
  move: Move,
  mousePointer: MousePointer,
  restore: RotateCcw,
  
  // Security & System
  shield: Shield,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  eyeOff: EyeOff,
  alert: AlertTriangle,
  globe: Globe,
  monitor: Monitor,
  palette: Palette,
  puzzle: Puzzle,
  
  // Text Formatting
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  subscript: Subscript,
  superscript: Superscript,
  highlighter: Highlighter,
  type: Type,
  smile: Smile,
  
  // Academic
  gradCap: GraduationCap,
  code: Code,
  telegram: Send,
  repeat: RoutineIcon
};

// Custom wrapper for Repeat icon
function RoutineIcon(props: any) {
    return <Repeat {...props} />
}

interface IconProps {
  name: string;
  size?: number;
  className?: string;
}

export const Icon: React.FC<IconProps> = ({ name, size = 20, className = "" }) => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const LucideIcon = (icons as any)[name] || (icons as any)['fileText']; 
  
  if (!LucideIcon) {
      console.warn(`Icon "${name}" not found, falling back to FileText.`);
      return <FileText size={size} className={className} />;
  }

  return <LucideIcon size={size} className={className} />;
};
